swagger: "2.0"
info:
  version: "0.0.1"
  title: VIA server App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /events:
    # binds a127 app logic to a route
    x-swagger-router-controller: events
    get:
      description: Returns 10 upcoming events
      # used as the method name of the controller
      operationId: events
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/EventsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /team:
    # binds a127 app logic to a route
    x-swagger-router-controller: team
    get:
      description: list of all players (for now - should be only 'active' or based on status)
      # used as the method name of the controller
      operationId: team
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TeamResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  EventsResponse:
    required:
      - message
    properties:
      message:
        type: string
  TeamResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
